### ISSUE TITLE
Cant' install aldryn-blog

### ISSUE THREAD

**Issue by csoliss** [aldryn/aldryn-blog#84]
I have this package
# pip freeze
aldryn-blog==0.5.0
aldryn-common==0.0.6
dj-database-url==0.3.0
Django==1.6.9
django-appconf==0.6
django-appdata==0.1.3
django-classy-tags==0.5.2
django-cms==3.0.7
django-filer==0.9.8
django-hvad==1.0.0
django-mptt==0.6.1
django-polymorphic==0.6.1
django-reversion==1.8.5
django-sekizai==0.7
Django-Select2==4.2.2
django-taggit==0.11.2
djangocms-admin-style==0.2.5
djangocms-column==1.5
djangocms-file==0.1
djangocms-flash==0.1
djangocms-googlemap==0.2
djangocms-inherit==0.1
djangocms-installer==0.6.0
djangocms-link==1.5
djangocms-picture==0.1
djangocms-style==1.5
djangocms-teaser==0.1
djangocms-text-ckeditor==2.4.3
djangocms-video==0.1
html5lib==0.999
Pillow==2.7.0
psycopg2==2.5.4
pytz==2014.10
requests==2.5.1
six==1.9.0
South==1.0.2
Unidecode==0.4.17

# pip install aldryn-blog
...
Collecting django-mptt==0.5.2,==0.6,==0.6.1 (from django-filer->aldryn-blog)
  Could not find a version that satisfies the requirement django-mptt==0.5.2,==0.6,==0.6.1 (from django-filer->aldryn-blog) (from versions: 0.1, 0.2, 0.2.1, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.6.1)
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external to allow).
  No distributions matching the version for django-mptt==0.5.2,==0.6,==0.6.1 (from django-filer->aldryn-blog)

or if i try o it with the source code

# git clone https://github.com/aldryn/aldryn-blog.git
# cd aldryn-blog/
# python setup.py install
...
No local packages or download links found for django-mptt==0.5.2,==0.6,==0.6.1
error: Could not find suitable distribution for Requirement.parse('django-mptt==0.5.2,==0.6,==0.6.1')

what i am doing wrong?

**Comment by HadrienMP** [comment]
In case someone stumbles upon this same error, I just had it and fixed it by removing the version after django-filer and django-mptt in my requirements.txt. Then I launched pip install -r requirements.txt --upgrade.

When I reentered pip install aldryn-blog it installed perfectly.

I guess the problem was that I didn't have the last available django-filer version.
